version: "3"

volumes:
  sockets:

networks:
  drops:

services:

  core:
    image: drops/core
    restart: always
    build:
      context: core
      dockerfile: Dockerfile
    volumes:
      - sockets:/tmp/sockets
    depends_on:
      - server
    networks:
      - drops

  server:
    image: drops/server
    container_name: server
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - sockets:/tmp/sockets
    ports:
      - "7000:7000"
    environment:
      - SOCKET_TO_NODE=/tmp/sockets/drops_to_node.sock
      - SOCKET_FROM_NODE=/tmp/sockets/drops_from_node.sock
      - NODE_ENV=production
    networks:
      - drops

  frontend:
    image: drops/frontend
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "7002:7002"
    environment:
      - VITE_MULTIPLAYER_HOST_GAME=ws://localhost/server
    networks:
      - drops

  http:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - drops